### ISSUE TITLE
QDC-CMIP6 file metadata

### ISSUE THREAD

**Issue by DamienIrving** [DamienIrving/qq-validation#5]
The file checker developed by @malcolmking currently gives the following report for a typical precipitation QDC-CMIP6 data file. In this issue we'll discuss whether and how to address each of the issues flagged in the report.

```
==========================================
/g/data/ia39/australian-climate-service/test-data/QDC-CMIP6-v2/BARRA-R2/ACCESS-CM2/ssp245/r4i1p1f1/day/pr/2035-2064/
pr_day_ACCESS-CM2_ssp245_r4i1p1f1_AUS-11_2035_qdc-multiplicative-monthly-q100-linear-maxaf5-annual-change-matched_BARRA-R2-baseline-1985-2014_model-baseline-1985-2014.nc
==========================================
Filename/content match check:
------------------------------------------  
Data variable matches filename: True
Data temporal frequency matches filename: True
Source model matches filename: True
Source experiment matches filename: True
Source varient matches filename: True
Data timerange matches filename: True

Grid check:
------------------------------------------
Lat-lon grid matches BARRA-R2: True

Missing data check:
------------------------------------------
No missing data: True

Data range check:
------------------------------------------
Data in range: True

CF-standard metadata check results
------------------------------------------
==High priority results==
§3.3 Standard Name: standard_name precipitation is not defined in Standard Name Table v72. Possible close match(es): ['precipitation_flux', 'precipitation_amount', 'lwe_precipitation_rate']

==Medium priority results==
No issues

==Low priority results==
No issues


ACDD-standard metadata check results
------------------------------------------
==High priority results==
variable "pr" missing the following attributes:: coverage_content_type

==Medium priority results==
Global Attributes: id not present
Global Attributes: naming_authority not present
Global Attributes: creator_url not present
Global Attributes: project not present
Global Attributes: geospatial_vertical_min not present
Global Attributes: geospatial_vertical_max not present
Global Attributes: time_coverage_start not present
Global Attributes: time_coverage_end not present
Global Attributes: time_coverage_duration not present
Global Attributes: standard_name_vocabulary not present
Global Attributes: geospatial_vertical_positive not present
Global Attributes: geospatial_bounds_vertical_crs not present
Global Attributes: publisher_email not present
date_created_is_iso: Attr date_created is not present

==Low priority results==
No issues

```

**Comment by DamienIrving** [comment]
Proposed actions...

### Variable attributes
- [ ] Switch the `standard_name` variable attribute in all precipitation files from `precipitation` to `lwe_precipitation_rate` (my hesitation in not doing this previously is that nobody will know that lwe stands for liquid water equivalent).
- [ ] Do not include `coverage_content_type` as a variable attribute

### Global attributes
Do not include:
- [ ] `id` (if we did it would be after we have a DOI for the dataset) 
- [ ] `naming_authority` (if we did it would be after we know which authority issues the DOI for the dataset)
- [ ] `standard_name_vocabulary` (not sure what this is)
- [ ] `geospatial_vertical_positive` (no vertical coordinate)
- [ ] `geospatial_bounds_vertical_crs` (no vertical bounds)
- [ ] `publisher_email` (we already have email addresses in the `contact` and `creator_email` attributes) 
- [ ] `geospatial_vertical_min` (all the variables are surface)
- [ ] `geospatial_vertical_max` (all the variable are surface)

Create/add new attributes for:
- [ ] `creator_url = https://www.acs.gov.au/`
- [ ] `project = QDC-CMIP6`
- [ ] `time_coverage_start` (e.g. `20350101T0000Z`)
- [ ] `time_coverage_end` (e.g. `20351231T0000Z`)
- [ ] `time_coverage_duration` (e.g. `P1Y0M0DT0H0M0S` following the ISO 8601:2004 duration format)

**Comment by DamienIrving** [comment]
I think we also need to append the following sentences to the end of the `summary` global attribute in AGCD scaled QDC-CMIP6 data files for tasmin, tasmax and pr respectively:
- "The AGCD minimum temperature for the previous 24 hours is recorded at 9am local clock time and then recorded against the observed day\'s date."
- "The AGCD maximum temperature for the previous 24 hours is recorded at 9am local clock time and then recorded against the previous day\'s date."
- "The AGCD precipitation for the previous 24 hours is recorded at 9am local clock time and then recorded against the observed day\'s date."

I couldn't find information on the conventions for the BARRA-R2 dataset, so I think we'll just leave those files unchanged.

**Comment by DamienIrving** [comment]
We also need to update the `processing_level` attribute now that the data checks have been applied. It currently reads: 

`Level 1a: Post-processing of output Level 0 scaled data with robust metadata and data reference syntax applied, but no quality assurance and quality control undertaken.`

**Comment by malcolmking** [comment]
> Proposed actions...
> 
> ### Variable attributes
> * [ ]  Switch the `standard_name` variable attribute in all precipitation files from `precipitation` to `lwe_precipitation_rate` (my hesitation in not doing this previously is that nobody will know that lwe stands for liquid water equivalent).
> * [ ]  Do not include `coverage_content_type` as a variable attribute
> 
> ### Global attributes
> Do not include:
> 
> * [ ]  `id` (if we did it would be after we have a DOI for the dataset)
> * [ ]  `naming_authority` (if we did it would be after we know which authority issues the DOI for the dataset)
> * [ ]  `standard_name_vocabulary` (not sure what this is)
> * [ ]  `geospatial_vertical_positive` (no vertical coordinate)
> * [ ]  `geospatial_bounds_vertical_crs` (no vertical bounds)
> * [ ]  `publisher_email` (we already have email addresses in the `contact` and `creator_email` attributes)
> * [ ]  `geospatial_vertical_min` (all the variables are surface)
> * [ ]  `geospatial_vertical_max` (all the variable are surface)
> 
> Create/add new attributes for:
> 
> * [ ]  `creator_url = https://www.acs.gov.au/`
> * [ ]  `project = QDC-CMIP6`
> * [ ]  `time_coverage_start` (e.g. `20350101T0000Z`)
> * [ ]  `time_coverage_end` (e.g. `20351231T0000Z`)
> * [ ]  `time_coverage_duration` (e.g. `P1Y0M0DT0H0M0S` following the ISO 8601:2004 duration format)

I agree with these proposed actions apart from not including `coverage_content_type`, which is highly recommended for ACDD/ISO compliance. I think this should be set as `modelResult` for all variables (this defines the source/type of data for the variable, and for almost everything we produce, it'll either be `modelResult` or `physicalMeasurement`).

We could also include `standard_name_vocabulary` with `CF Standard Name Table v86` as the value - this states our list of acceptable standard_names is the current CF list. It's not required, but it's no real additional effort.

**Comment by malcolmking** [comment]
> We also need to update the `processing_level` attribute now that the data checks have been applied. It currently reads:
> 
> `Level 1a: Post-processing of output Level 0 scaled data with robust metadata and data reference syntax applied, but no quality assurance and quality control undertaken.`

Seeing we labelled the pre-QA data as Level 1a (and we don't seem to have institutional data processing levels), should we use something like:
`Level 1b: Post-processing of output Level 0 scaled data with robust metadata and data reference syntax applied and a quality assurance and quality control check undertaken.`?

**Comment by DamienIrving** [comment]
That all sounds good to me, @malcolmking. I'll go ahead and run my update script for a single file and send you the path to take a look.
